name: Change Shell
on: push
jobs:
  change-shell-job:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "${SHELL}"
      - shell: python
        run: |
          import os
          print(os.environ['PATH'])
